---

- name: Converge
  hosts: all
  become: true

  vars:
    wifi_login_pages_domains: ["localhost"]

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install gpg agent
      apt:
        name: gpg-agent
        update_cache: true

    - name: Install git
      apt:
        name: git
        update_cache: true

    - name: Install supervisor
      apt:
        name: supervisor
        update_cache: true

    - name: Install nginx
      apt:
        name: nginx
        update_cache: true

  tasks:
    - name: "Include ansible role"
      include_role:
        name: "ansible-openwisp-wifi-login-pages"
